apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-namenode"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: "{{ template "fullname" . }}-namenode"
spec:
  ports:
  - port: {{ .Values.service.internalPort }}
    name: {{ .Values.service.name }}
  clusterIP: None
  selector:
    app: "{{ template "fullname" . }}-namenode"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-webui"
  labels:
    app: "{{ template "fullname" . }}-webui"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
  selector:
    app: "{{ template "fullname" . }}-namenode"
