apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-datanode"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: "{{ template "fullname" . }}-datanode"
spec:
  ports:
  - port: {{ .Values.service.dataPort }}
    name: {{ .Values.service.name }}
  clusterIP: None
  selector:
    app: "{{ template "fullname" . }}-datanode"
